version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: insightcrawler-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rutvik@416
      MYSQL_DATABASE: insightcrawler
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
